.TH LIBUNINAMESLIST 3 "2003-Jan-16"
.SH NAME
libuninameslist \- Unicode Names and Annotations List
.SH SYNOPSIS
.B #include <uninameslist.h>
.br
Compile and link with
.I -luninameslist
.br
.SH DESCRIPTION
The
.B libuninameslist
library provides the ability for a program to fetch unicode
.B names
and
.B annotations
as described by www.unicode.org in a text file called
.B NamesList.txt
.SH OPTIONS
This library package comes with an optional Python wrapper
called
.I uninameslist.py
and an optional French nameslist library called
.I libuninameslist\-fr
.SH AUTHOR
Read
.I AUTHORS
file for everyone involved in making
.B libuninameslist
