.TH LIBUNINAMESLIST\-FR 3 "2018-Jun-08"
.SH NAME
libuninameslist\-fr \- Unicode Names and Annotations List - French
.SH SYNOPSIS
.B #include <uninameslist\-fr.h>
.br
Compile and link with
.I -luninameslist\-fr
.br
.SH DESCRIPTION
The
.B libuninameslist\-fr
library provides the ability for a program to fetch French
translations of unicode
.B names
and
.B annotations
as described by www.unicode.org in a text file called
.B NamesList.txt
which has been translated to French
.B ListeDesNoms.txt
by several volunteer translators.
.SH OPTIONS
This library package comes with an optional Python wrapper
called
.I uninameslist.py
and the main
.I libuninameslist
library.
.SH SEE ALSO
\fBlibuninameslist\fP(3)
.SH AUTHOR
Read
.I AUTHORS
file for everyone involved in making
.B libuninameslist\-fr
and translators involved in creating the French translations
.B ListeDesNoms.txt
